config/routes.rb
Rails.application.routes.draw do
  get 'static/about'
  resources :cars, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Rutas para Home y About
  root 'cars#index' # O la acción que desees como página principal
  get 'about', to: 'static#about' # Asumiendo que crearás un controlador llamado Static

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :rentals

  validates :brand, :model, :year, :price_per_day, presence: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :user_id, :car_id, :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :rentals

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      query = "%#{params[:query].downcase}%"
      @cars = Car.where("LOWER(brand) LIKE ? OR LOWER(model) LIKE ?", query, query).page(params[:page]).per(15)
    else
      @cars = Car.page(params[:page]).per(15)
    end
  end

  def show
    @car = Car.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/cars/index.html.erb
<h1>Cars Available for Rent</h1>
<div class="form-container">
    <%= form_with(url: cars_path, method: :get, local: true, html: { class: 'search-form' }) do %>
        <div class="form-group">
            <%= label_tag :query, "Search Cars:" %>
            <%= text_field_tag :query, params[:query], placeholder: "Enter brand, model, etc." %>
            <%= submit_tag "Search" %>
        </div>
    <% end %>
</div>


<div class="cars-list">
    <ul>
        <% @cars.each do |car| %>
            <li>
                <%= car.brand %> <%= car.model %> -
                <%= link_to "See details", car_path(car) %>
            </li>
        <% end %>
    </ul>

    <%= paginate @cars %>
</div>

app/views/cars/show.html.erb
<div class="car-detail-container">
    <h2>Car Details</h2>
    <p><strong>Brand:</strong><%= @car.brand %></p>
    <p><strong>Model:</strong><%= @car.model %></p>
    <p><strong>Year:</strong> <%= @car.year %></p>
    <p><strong>Price per day:</strong> $<%= @car.price_per_day %></p>
    <%= link_to 'Back to Cars', cars_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CarRental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="menu-container">
        <%= link_to image_tag('logo_car_rental.png', class: 'logo', alt: 'Car Rental Logo'), root_path %>
        <nav>
          <ul>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', about_path %></li>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>
  </body>
</html>